---
title: "Installations"
date: 2021-07-31T19:07:25+02:00
#draft: true
s9: true
math: true
tags: ["meta","tech","coding","web", "software"]
categories: ["post","readme","test"]
img: oscar-wilde.jpeg
---

== Installation of this site

===  Install Hugo
[source, shell]
----
>git clone https://github.com/gohugo.io/hugo.git
>cd hugo
>brew install go
>go install --tags extended
----
  
=== Install InfiniteInk's _themeless-gitless-intro-hugo_
[source, shell]
----
>git clone https://github.com/infiniteink/themesless-gitless-intro-hugo.git
>hugo server -D --gc --disableFastRender
----
=== Install _Asciidoctor_
----
>brew install Asciidoctor
>brew install ruby
>brew install brew-gem

----
. create asciidoctor executable shell
----
#!/bin/bash
if [ -f /usr/local/bin/asciidoctor ]; then
  ad="/usr/local/bin/asciidoctor"
else
  ad="/usr/bin/asciidoctor"
fi

$ad -B . -r asciidoctor-diagram -a icons=font -a docinfo=shared -a nofooter -a sectanchors -a experimental=true -a figure-caption! -a source-highlighter=highlightjs -a toc-title! -a stem=mathjax - | sed -E -e "s/img src=\"([^/]+)\"/img src=\"\/diagram\/\1\"/"

mkdir -p static/diagram

if ls *.svg >/dev/null 2>&1; then
  mv -f *.svg static/diagram
fi

if ls *.png >/dev/null 2>&1; then
  mv -f *.png static/diagram
fi
----

=== Install _Pandoc¨
----
brew install pandoc
brew install library python homebrew /cask/basictex
tlmgr install collection-fontsrecommended
----
. create hugo executable shell
----
!/bin/bash

export PANDOC_ORIGINAL=$(which pandoc)

# Overrides pandoc.
PATH=$PWD/bin:$PATH

hugo "$@"
----

cheatsheet: 
{{< embed-pdf url="../test/pandocCheatSheet.pdf"  >}}



=== Adapt _config.yaml_ file

{{< showhide id="config" >}}


{{< /showhide >}}

=== add S9 Sharebuttons panel
 - add partials/s9-widget-wrapper.html
----
<!-- layouts/partials/s9-widget-wrapper.html -->
<!-- the following script is to be put in the head part of the html -->
<!-- script id="s9-sdk" async defer 
content="33fbf926f45e4d42afe4e864df7e1fda" 
src="//cdn.social9.com/js/socialshare.min.js">
</script -->

{{ if or .Params.s9 .Site.Params.s9 }}
    {{ i18n  "shareThisArticle" }}
    <div class="s9-widget-wrapper"></div>
{{ end }}

----

 - add s9 variable to config.yaml
 - add s9-sdk script to partials/head-scripts.html
 - add s9-wrapper to partials/header-scripts.html
----

=== create Mathjax partial file
----
<!-- layouts/partials/math.html -->
{{ if or .Params.math .Site.Params.math }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_SVG"></script>
<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
            showMathMenu: false, //disables context menu
            tex2jax: {
            inlineMath: [ ['$','$'], ['\\(','\\)'] ]
           }
    });
</script>
{{ end }}
----
 - add invoking script in partial/header-scripts.html
 - add invoking script in partials/post-preview.html
 - add math variable in config.yaml
----

=== Add Webjeda theme
to set posts into visual Cards
----
$ cd themes
$ git submodule add https://github.com/tran62/hugo-cards.git
----
- theme forked from /bul-ikana/hugo-cards (for hugo) from /sharu725/cards (Webjeda)
- put hugo-cards theme as first theme in config.yaml
- enable scss in assets/sass in scripts in head-scripts.html partial
- enable bootstrap.js in head-scripts.html partial
----
<script src="js/bootstrap.min.js"></script>
----



=== Add Showhide partial block feature
add _showhide.html_ to layouts/shortcodes/
----
usage: 
{{/*< showhide id="unique-id">*/}}  
Text  in html to show/hide (remove the comments (/*, */) to enable feature)
{{/*< /showhide >*/}}
----

=== Add Hover term definition feature
add _tip.html_ and _def.html_ to layouts/shortcodes/
----
usage: {{tip}}your word{{def}}definition of word{{/def}}{{/tip}}
ex: test post in content/posts/
----
=== Add Embed-pdf feature
from: link:https://github.com/tran62/hugo-embed-pdf-shortcode[hugo-embed-pdf-shortcode]
A shortcode for Hugo(https://gohugo.io/) which allows you to embed a PDF file in a page using Pdf.js (https://mozilla.github.io/pdf.js/)

. clone hugo-embed-pdf-shortcode.git
. cd hugo-embed...
. cp ./layouts/shortcodes/embed-pdf.html in your Hugo website dir
. cp ./static/js/pdf-js/ directory to your ./static/js website dir

```
- cp -R ./static/js/pdf-js /your-hugo/static/js/
- usage: {{/*< embed-pdf url="toto.pdf" >*/}}  (remove the /* comment brackets)
```

=== Add Search feature
from link:https://victoria.dev/blog/add-search-to-hugo-static-sites-with-lunr/[victoria.dev/blog/add-search-to-hugo-static-sites-with-lunr/]

. create search-form.html partial
. include this partial into layouts/search/
. create layouts/search/list.html template
. create content/search/_index.md page
. build search-index partial into footer partial
. create static/js/search.js script file
. create content/search/_index.md page (frontmatter only)

=== Git Large file Storage
from link: https://git-lfs.github.com/[Git LFS]

. brew install git-lfs
. git lfs install
. git lfs track "*.pdf"
. git add .gitattributes

. then just add commit and push to GitHub as you normally would
'''(zsh)
git add file.pdf
git commit -m "Add pdf file"
git push origin master
'''

=== Convert hanzi to calligraphic

. Akizuti Converter, Hanzi to calligraphy, link:http://www.akuziti.com/mb/[Akuziti calligraphy converter] _choose option 39 - put result to Cmd-shift-4 screen copy or Gimp to convert to png/jpg image_
=== current projects
. embed epub on web page link:https://github.com/futurepress/epub.js[github/futurepress]
. epub theme for Hugo link:https://github.com/weitblick/epub[weitblick]
. asciidoc to epub link:https://github.com/asciidoctor/asciidoctor-epub3[asciidoctor-epub3]


___

