#baseURL: https://awesome-archimedes.netlify.app/
#baseURL: "http://qat.local/"
baseURL: http://localhost:1313/
languageCode: fr
title: hugascii
math: true
s9: true
st: false
ft: false
protected: true
theme :
  - hugotran-theme
themedir : ../..

params:
  search: true
  paginate: 7
  custom_css:
    - css/custom.css
  builtBy: tran62
  defaultImage: gopher.jpg

  facebook: "https://facebook.com/qatran75"
  quora: 
  twitter: "https://twitter.com/qatran"
  github: "https://github.com/tran62"
  email: qat@melix.net

  fbLikeBox: 
  fbAppId: 
  fbPageUrl: 
  fbPageTitle: 

  disqus: 
  
security:
  enableInlineShortcodes: false
  exec:
    allow:
    - ^dart-sass-embedded$
    - ^go$
    - ^npx$
    - ^postcss$
    - ^asciidoctor$
    - ^pandoc$
    osEnv:
    - (?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$


  security.funcs:
    getenv: ^HUGO_

  security.http:
    methods: (?i)GET|POST
    urls: .*

markup:
  preserveTOC: false
  workingFolderCurrent: false  # default is false

  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false

  asciidocExt:
    preserveTOC: false
    workingFolderCurrent: false  # default is false
    backend: html5
    extensions: []
    failureLevel: fatal
    noHeaderOrFooter: true
    safeMode: safe
    sectionNumbers: false
    trace: false
    verbose: false

    attributes:
      toc: auto
      hide-uri-scheme: true@  # trailing @ means ok to override
      sectlinks: true
      huri-config-vars: https://gohugo.io/getting-started/configuration/
      huri-page-vars: https://gohugo.io/variables/page/
      huri-site-vars: https://gohugo.io/variables/site/
      huri-file-vars: https://gohugo.io/variables/files/
      imagesdir: 
  pandoc:
    mathjax: true
    
defaultMarkdownHandler: "adoc"

privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: false
    disable: false
    respectDoNotTrack: false
    useSessionStorage: false
  instagram:
    disable: false
    simple: false
  twitter:
    disable: false
    enableDNT: false
    simple: false
  vimeo:
    disable: false
    enableDNT: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: false
